before_install:
 - sudo apt-get update -qq && sudo apt-get install -y libaio1
 - sudo hostname "$(hostname | cut -c1-63)"

os: linux
dist: trusty
sudo: required

language: scala
scala: "2.10.5"
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.wixMySQL

script:
  - sbt ++${TRAVIS_SCALA_VERSION} test
  - sbt scripted
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
  - if [[ ${JAVA_HOME} == $(jdk_switcher home oraclejdk7) ]]; then rm -rf $HOME/.ivy2/cache ; fi
